# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continous Integration NextJS Boiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run lint:scripts
      - run: npm run build
      - run: npm run test

    env:
      CI: true
      DB_HOST: ${{ secrets.DB_ENDPOINT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      APPKEY: ${{ secrets.APPKEY }}
      APPNAME: ${{ secrets.APPNAME }}
      APM_TOKEN: ${{ secrets.APM_TOKEN }}
      APM_SERVER_HOST: ${{ secrets.APM_SERVER_HOST }}
      ENABLE_LOGGING_APM: ${{ secrets.ENABLE_LOGGING_APM }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_IP: ${{ secrets.REDIS_IP }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
